let list = [
  {
    _id: 1,
    title: "Strong English Breakfast",
    img: "../../images/BlackTea/B01.jpg",
    price: "500",
    category: "b",
    discount: "2",
  },
  {
    _id: 2,
    title: "Strong English Breakfast",
    img: "../../images/BlackTea/B02.jpg",
    price: "1000",
    category: "b",
    discount: "5",
  },
  {
    _id: 3,
    title: "Strong English Breakfast",
    img: "../../images/BlackTea/B03.jpg",
    price: "5000",
    category: "b",
    discount: "10",
  },
  {
    _id: 4,
    title: "Strong English Breakfast",
    img: "../../images/BlackTea/B04.jpg",
    price: "150000",
    category: "b",
    discount: "30",
  },
  {
    _id: 5,
    title: "Strong English Breakfast",
    img: "../../images/BlackTea/B05.jpg",
    price: "1500",
    category: "b",
    discount: "0",
  },
  {
    _id: 6,
    title: "Strong English Breakfast",
    img: "../../images/BlackTea/B06.jpg",
    price: "500000",
    category: "b",
    discount: "20",
  },
  {
    _id: 7,
    title: "Inner Peace Sweet",
    img: "../../images/Superblends/S01.jpg",
    price: "3000",
    category: "s",
    discount: "0",
  },
  {
    _id: 8,
    title: "Inner Peace Sweet",
    img: "../../images/Superblends/S02.jpg",
    price: "4000",
    category: "s",
    discount: "10",
  },
  {
    _id: 9,
    title: "Inner Peace Sweet",
    img: "../../images/Superblends/S03.jpg",
    price: "100000",
    category: "s",
    discount: "10",
  },
  {
    _id: 10,
    title: "Inner Peace Sweet",
    img: "../../images/Superblends/S04.jpg",
    price: "8000",
    category: "s",
    discount: "10",
  },
  {
    _id: 11,
    title: "Inner Peace Sweet",
    img: "../../images/Superblends/S05.jpg",
    price: "8000",
    category: "s",
    discount: "10",
  },
  {
    _id: 12,
    title: "Inner Peace Sweet",
    img: "../../images/Superblends/S06.jpg",
    price: "8000",
    category: "s",
    discount: "10",
  },
  {
    _id: 13,
    title: "Inner Peace Sweet",
    img: "../../images/Superblends/S07.jpg",
    price: "8000",
    category: "s",
    discount: "10",
  },
  {
    _id: 14,
    title: "Inner Peace Sweet",
    img: "../../images/Superblends/S08.jpg",
    price: "8000",
    category: "s",
    discount: "10",
  },
  {
    _id: 15,
    title: "Earl Grey",
    img: "../../images/EarlGreyTea/E01.jpg",
    price: "8000",
    category: "e",
    discount: "10",
  },
  {
    _id: 16,
    title: "Earl Grey",
    img: "../../images/EarlGreyTea/E02.jpg",
    price: "8000",
    category: "e",
    discount: "10",
  },
  {
    _id: 17,
    title: "Earl Grey",
    img: "../../images/EarlGreyTea/E03.jpg",
    price: "8000",
    category: "e",
    discount: "10",
  },
  {
    _id: 18,
    title: "Lady Grey",
    img: "../../images/EarlGreyTea/E04.jpg",
    price: "8000",
    category: "e",
    discount: "10",
  },
  {
    _id: 19,
    title: "Lady Grey",
    img: "../../images/EarlGreyTea/E05.jpg",
    price: "8000",
    category: "e",
    discount: "10",
  },
  {
    _id: 20,
    title: "Lady Grey",
    img: "../../images/EarlGreyTea/E06.jpg",
    price: "8000",
    category: "e",
    discount: "10",
  },
];
export default list;
